language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

env:
  matrix:
    - WAYLAND_VERSION="1.8.1"
  global:
    - LD_LIBRARY_PATH=${HOME}/wayland/lib
    - LIBRARY_PATH=${HOME}/wayland/lib
    - CPATH=${HOME}/wayland/include
    - XDG_RUNTIME_DIR=/tmp

matrix:
  allow_failures:
    - python: pypy
    - python: pypy3

before_install:
  - wget http://wayland.freedesktop.org/releases/wayland-${WAYLAND_VERSION}.tar.xz
  - tar -xJf wayland-${WAYLAND_VERSION}.tar.xz
  - pushd wayland-${WAYLAND_VERSION}
  - ./configure --disable-documentation --prefix=${HOME}/wayland
  - make
  - make install
  - popd

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
      pip install -r requirements-3.4+.txt;
    else
      pip install -r requirements-2-3.3.txt;
    fi
  - python setup.py generate_protocol --xml-file=${HOME}/wayland/share/wayland/wayland.xml
  - python setup.py build_ext --inplace

script:
  - flake8 --config flake8.cfg pywayland/ tests/
  - py.test --cov pywayland --cov-report term-missing

after_success:
  - coveralls

notifications:
  email: false
