language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

env:
  global:
    - LD_LIBRARY_PATH=${HOME}/wayland/lib
    - LIBRARY_PATH=${HOME}/wayland/lib
    - CPATH=${HOME}/wayland/include

before_install:
  - wget http://wayland.freedesktop.org/releases/wayland-1.7.0.tar.xz
  - tar xJf wayland-1.7.0.tar.xz
  - pushd wayland-1.7.0
  - ./configure --disable-documentation --prefix=${HOME}/wayland
  - make
  - make install
  - popd

install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* || $TRAVIS_PYTHON_VERSION == '3.2' || $TRAVIS_PYTHON_VERSION == '3.3' ]]; then
      pip install -r requirements-2-3.3.txt;
    elif [[ $TRAVIS_PYTHON_VERSION == '3.4' ]]; then
      pip install -r requirements-3.4+.txt;
    elif [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
      pip install -r requirements-pypy.txt;
    else
      exit 1;
    fi
  - python ./bin/pywayland-scanner.py -i ${HOME}/wayland/share/wayland/wayland.xml

script:
  - flake8 --config flake8.cfg pywayland/ tests/ bin/
  - py.test --cov pywayland --cov-report term-missing

after_success:
  - coveralls

notifications:
  - email: false
