language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27 WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: 3.3
      env: TOXENV=py33 WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: 3.4
      env: TOXENV=py34 WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: 3.5
      env: TOXENV=py35 WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: pypy
      env: TOXENV=pypy WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: pypy3
      env: TOXENV=pypy3 WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: nightly
      env: TOXENV=nightly WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: 2.7
      env: TOXENV=pep8 WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: 3.5
      env: TOXENV=pep8 WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: 3.5
      env: TOXENV=docs WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
  allow_failures:
    - python: nightly
      env: TOXENV=nightly WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0
    - python: 3.5
      env: TOXENV=docs WAYLAND_VERSION=1.9.0 WAYLAND_PROTOCOLS=1.0

env:
  global:
    - CPATH="${HOME}/wayland/include"
    - LD_LIBRARY_PATH="${HOME}/wayland/lib"
    - LIBRARY_PATH="${HOME}/wayland/lib"
    - PKG_CONFIG_PATH="${HOME}/wayland/share/pkgconfig:${HOME}/wayland/lib/pkgconfig"
    - XDG_RUNTIME_DIR="/tmp"

install:
# build Wayland
  - wget http://wayland.freedesktop.org/releases/wayland-${WAYLAND_VERSION}.tar.xz
  - tar -xJf wayland-${WAYLAND_VERSION}.tar.xz
  - pushd wayland-${WAYLAND_VERSION}
  - ./configure --disable-documentation --prefix=${HOME}/wayland
  - make
  - make install
  - popd
# build Wayland-protocols
  - wget http://wayland.freedesktop.org/releases/wayland-protocols-${WAYLAND_PROTOCOLS}.tar.xz
  - tar -xJf wayland-protocols-${WAYLAND_PROTOCOLS}.tar.xz
  - pushd wayland-protocols-${WAYLAND_PROTOCOLS}
  - ./configure --prefix=${HOME}/wayland
  - make
  - make install
  - popd
# install tox for us
  - pip install tox

script:
  - tox
