language: python
cache:
  pip: true
  directories:
    - wayland_dl

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
  - nightly

matrix:
  include:
    - python: 2.7
      env: TEST=pep8 WAYLAND_VERSION=1.14.0 WAYLAND_PROTOCOLS=1.11
    - python: 3.6
      env: TEST=pep8 WAYLAND_VERSION=1.14.0 WAYLAND_PROTOCOLS=1.11
    - python: 3.6
      env: TEST=docs WAYLAND_VERSION=1.14.0 WAYLAND_PROTOCOLS=1.11
  allow_failures:
    - python: nightly

env:
  global:
    - CPATH="${HOME}/wayland/include"
    - LD_LIBRARY_PATH="${HOME}/wayland/lib"
    - LIBRARY_PATH="${HOME}/wayland/lib"
    - PKG_CONFIG_PATH="${HOME}/wayland/share/pkgconfig:${HOME}/wayland/lib/pkgconfig"
    - XDG_RUNTIME_DIR="/tmp"
    - WAYLAND_URL='http://wayland.freedesktop.org/releases/wayland-${WAYLAND_VERSION}.tar.xz'
    - WAYLAND_PROTOCOLS_URL='http://wayland.freedesktop.org/releases/wayland-protocols-${WAYLAND_PROTOCOLS}.tar.xz'
    - PYPY_VERSION=5.6.0
    - PYPY3_VERSION=5.5.0
  matrix:
    - WAYLAND_VERSION=1.14.0 WAYLAND_PROTOCOLS=1.11

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then
        if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
            export PYPY_FILE=pypy2-v${PYPY_VERSION}-linux64;
        else
            export PYPY_FILE=pypy3.3-v${PYPY3_VERSION}-alpha-linux64;
        fi;
        pushd ~;
        wget https://bitbucket.org/pypy/pypy/downloads/${PYPY_FILE}.tar.bz2;
        tar -xjf ${PYPY_FILE}.tar.bz2;
        if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
            export PATH=~/${PYPY_FILE}/bin:$PATH;
            ln -s pypy ${PYPY_FILE}/bin/python;
        else
            export PATH=~/pypy3-v${PYPY3_VERSION}-linux64/bin:$PATH;
            ln -s pypy3 pypy3-v${PYPY3_VERSION}-linux64/bin/python;
        fi;
        hash -r;
        curl -O https://bootstrap.pypa.io/get-pip.py;
        python get-pip.py;
        popd;
    fi

install:
  - WAYLAND_URL=`echo $WAYLAND_URL | envsubst`
  - WAYLAND_PROTOCOLS_URL=`echo $WAYLAND_PROTOCOLS_URL | envsubst`
  - if [[ ! -f wayland_dl/wayland-${WAYLAND_VERSION}.tar.xz ]]; then
        wget --no-check-certificate -P wayland_dl $WAYLAND_URL;
    fi
  - if [[ ! -f wayland_dl/wayland-protocols-${WAYLAND_PROTOCOLS_VERSION}.tar.xz ]]; then
        wget --no-check-certificate -P wayland_dl $WAYLAND_PROTOCOLS_URL;
    fi
# build Wayland
  - tar -xJf wayland_dl/wayland-${WAYLAND_VERSION}.tar.xz
  - pushd wayland-${WAYLAND_VERSION}
  - ./configure --disable-documentation --prefix=${HOME}/wayland
  - make
  - make install
  - popd
# build Wayland-protocols
  - tar -xJf wayland_dl/wayland-protocols-${WAYLAND_PROTOCOLS}.tar.xz
  - pushd wayland-protocols-${WAYLAND_PROTOCOLS}
  - ./configure --prefix=${HOME}/wayland
  - make
  - make install
  - popd
# install necessary packages
  - pip install -r requirements.txt;
  - python pywayland/ffi_build.py;
  - python -m pywayland.scanner --with-protocols;
  - if [[ $TEST == pep8 ]]; then
        pip install flake8;
    elif [[ $TEST == docs ]]; then
        pip install -r doc/requirements.txt;
    else
        pip install -r requirements-dev.txt;
    fi

script:
  - if [[ $TEST == pep8 ]]; then
        flake8 pywayland example test;
    elif [[ $TEST == docs ]]; then
        sphinx-build -W -b html doc doc/_build/html;
    else
        py.test --cov pywayland --cov-report term-missing;
    fi

after_success:
  - if [[ -z $TEST ]]; then coveralls; fi
