name: Publish to PyPI
on:
  push:
    branches-ignore: ['*']
    tags: ['*']
  release:
    types: [published]
jobs:
  build-wayland:
    name: Build Wayland libraries
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64
    env:
      wayland-version: "1.19.0"
      wayland-protocols-version: "1.21"
    steps:
      - name: Install dependencies
        run: |
          apt update
          apt-get install -y --no-install-recommends \
            libexpat1-dev \
            libffi-dev \
            libxml++2.6-dev \
            wget \
            xsltproc \
            xz-utils
      - name: Download and unpack Wayland source
        run: |
          wget $WAYLAND_URL
          wget $WAYLAND_PROTOCOLS_URL
          tar -xJf wayland-${{ env.wayland-version }}.tar.xz
          tar -xJf wayland-protocols-${{ env.wayland-protocols-version }}.tar.xz
        env:
          WAYLAND_URL: https://wayland.freedesktop.org/releases/wayland-${{ env.wayland-version }}.tar.xz
          WAYLAND_PROTOCOLS_URL: https://wayland.freedesktop.org/releases/wayland-protocols-${{ env.wayland-protocols-version }}.tar.xz
      - name: Set environment variables
        run: |
          echo "CPATH=/wayland/usr/include" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/wayland/usr/lib" >> $GITHUB_ENV
          echo "LIBRARY_PATH=/wayland/usr/lib" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/wayland/usr/share/pkgconfig:/wayland/usr/lib/pkgconfig" >> $GITHUB_ENV
      - name: Build Wayland
        working-directory: wayland-${{ env.wayland-version }}
        run: |
          ./configure --disable-documentation --prefix=/usr
          make
          DESTDIR=/wayland make install
      - name: Build Wayland protocols
        working-directory: wayland-protocols-${{ env.wayland-protocols-version }}
        run: |
          ./configure --prefix=/usr
          make
          DESTDIR=/wayland make install
      - name: Create artifact
        run: tar czf /wayland.tar.gz -C /wayland/ .
      - name: Upload built libraries
        uses: actions/upload-artifact@v2
        with:
          name: wayland
          path: /wayland.tar.gz
          if-no-files-found: error
  build-wheel-cpython:
    name: Build CPython wheels
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux_2_24_x86_64
    needs: build-wayland
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: Download wayland libraries
        uses: actions/download-artifact@v2
        with:
          name: wayland
      - name: Unpack wayland artifact
        run: tar xf wayland.tar.gz -C /
      - name: Set environment variables
        run: |
          PYTHON_ROOT=$(find /opt/python -name cp${PYTHON_VERSION/./}-*)
          echo "${PYTHON_ROOT}/bin" >> $GITHUB_PATH
        shell: bash
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install Python dependencies
        run: |
          python --version
          python -m pip install -r requirements-wheel-build.txt
      - name: Build wheels
        run: |
          python pywayland/ffi_build.py
          python setup.py bdist_wheel --wayland-protocols
          auditwheel repair --plat manylinux2014_x86_64 -w output_wheels dist/pywayland-*.whl
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels-${{ matrix.python-version }}
          path: output_wheels/*.whl
      - name: Build source
        if: ${{ matrix.python-version == '3.9' }}
        run: |
          python setup.py sdist --wayland-protocols
      - name: Upload source
        uses: actions/upload-artifact@v2
        if: ${{ matrix.python-version == '3.9' }}
        with:
          name: source
          path: dist/*.tar.gz
  test-wheel:
    name: Test wheels
    runs-on: ubuntu-latest
    needs: build-wheel-cpython
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          name: wheels-${{ matrix.python-version }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install wheel
        run: pip install pywayland-*.whl
      - name: Check installation
        shell: python
        run: |
          import pywayland
          print(pywayland.__wayland_version__)
  upload-wheel:
    name: Upload wheels
    runs-on: ubuntu-latest
    needs: test-wheel
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v2
        with:
          name: wheels-${{ matrix.python-version }}
          path: dist/
      - name: Download source
        uses: actions/download-artifact@v2
        if: ${{ matrix.python-version == '3.9' }}
        with:
          name: source
          path: dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'release'
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push'
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
